name: Windows Qt6 Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - uses: lukka/run-vcpkg@v11
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.3'
          arch: 'win64_msvc2019_64'
          cache: true

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        run: vcpkg install winpty:x64-windows
      
      - name: Build dependencies
        run: |
          cmake -B build -G Ninja ^
            -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: Configure PtyQt
        run: cmake -B build -G Ninja

      - name: Build PtyQt
        run: cmake --build build
