name: Windows Qt6 Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.3'
          arch: 'win64_msvc2019_64'
          cache: true

      - uses: ilammy/msvc-dev-cmd@v1

      - run: cmake -B build -G Ninja
      - run: cmake --build build
